= wordle-101

== The road to a basic Wordle

=== 1. HTML skeleton

First of all, the HTML structure to support the game must be created. The document will consist of different areas:

* Title
* Explanation of the rules of the game
* Board where to display the accepted words
* Action panel
* List of all attempts (including non-validated ones)
* Footer

Start with a basic container for each row.

=== 2. More HTML elements

Now we are going to add new elements:

* Inputs, buttons and forms
* Lists

In this first phase you should not style the document. Simply focus on using the correct HTML elements and apply the appropriate classes and identifiers. You also do not have to create the __cell structure__ for the words in the table. That part will be refined later with other elements and styles.

=== 3. Apply basic CSS styles

In the following step simple styles will be applied to make the website more usable and better looking. 

Based on the sketches we will try to centre the content and make it "responsive" to some extent. Also we are going to style the buttons and the input elements. 

The introduction of custom text fonts and the use of background colors and shading will be an asset.

=== 4. Starting with Javascript

We are going to add a little dynamic behavior to our game:

* Store a list of possible words in an object / array
* At the start of the program, randomly select a word from the list to guess
* Allow the user to enter a word via input and, after pressing a button, issue an alert announcing whether they guessed correctly or not (with an exact word comparison)
* At this point, all the user's word attempts should be displayed in the lower list
* Put the current year in the footer near to the author information
